const SEARCH_SUGGESTIONS_REQUEST = 'Main nav search/SEARCH_SUGGESTIONS_REQUEST';
const SEARCH_SUGGESTIONS_SUCCESS = 'Api response/SEARCH_SUGGESTIONS_SUCCESS';
const SEARCH_SUGGESTIONS_ERROR = 'Api response/SEARCH_SUGGESTIONS_ERROR';


export default {
	SEARCH_SUGGESTIONS_REQUEST,SEARCH_SUGGESTIONS_SUCCESS,SEARCH_SUGGESTIONS_ERROR,

	
}