

const GET_CATEGORIES_REQUEST = 'Newmedia page/GET_CATEGORIES_REQUEST';
const GET_CATEGORIES_SUCCESS = 'Api response/GET_CATEGORIES_SUCCESS';
const GET_CATEGORIES_ERROR = 'Api response/GET_CATEGORIES_ERROR';




export default {
	GET_CATEGORIES_REQUEST,GET_CATEGORIES_SUCCESS,GET_CATEGORIES_ERROR,
}