

const CREATE_MEDIA_REQUEST = 'Newmedia page/CREATE_MEDIA_REQUEST';
const CREATE_MEDIA_SUCCESS = 'Api response/CREATE_MEDIA_SUCCESS';
const CREATE_MEDIA_ERROR = 'Api response/CREATE_MEDIA_ERROR';

const LIST_POPULAR_MEDIA_REQUEST = 'Home page/LIST_POPULAR_MEDIA_REQUEST';
const LIST_POPULAR_MEDIA_SUCCESS = 'Api response/LIST_POPULAR_MEDIA_SUCCESS';
const LIST_POPULAR_MEDIA_ERROR = 'Api response/LIST_POPULAR_MEDIA_ERROR';

const LIST_RELATED_MEDIA_REQUEST = 'Single media page/LIST_RELATED_MEDIA_REQUEST';
const LIST_RELATED_MEDIA_SUCCESS = 'Api response/LIST_RELATED_MEDIA_SUCCESS';
const LIST_RELATED_MEDIA_ERROR = 'Api response/LIST_RELATED_MEDIA_ERROR';

const READ_MEDIA_REQUEST = 'Single media page/READ_MEDIA_REQUEST';
const READ_MEDIA_SUCCESS = 'Api response/READ_MEDIA_SUCCESS';
const READ_MEDIA_ERROR = 'Api response/READ_MEDIA_ERROR';

const UPDATE_MEDIA_REQUEST = 'Edit media page/UPDATE_MEDIA_REQUEST';
const UPDATE_MEDIA_SUCCESS = 'Api response/UPDATE_MEDIA_SUCCESS';
const UPDATE_MEDIA_ERROR = 'Api response/UPDATE_MEDIA_ERROR';

const REMOVE_MEDIA_REQUEST = 'Edit media page/REMOVE_MEDIA_REQUEST';
const REMOVE_MEDIA_SUCCESS = 'Api response/REMOVE_MEDIA_SUCCESS';
const REMOVE_MEDIA_ERROR = 'Api response/REMOVE_MEDIA_ERROR';

export default {
	CREATE_MEDIA_REQUEST,CREATE_MEDIA_SUCCESS,CREATE_MEDIA_ERROR,

	LIST_RELATED_MEDIA_REQUEST,LIST_RELATED_MEDIA_SUCCESS,LIST_RELATED_MEDIA_ERROR,

	LIST_POPULAR_MEDIA_REQUEST,LIST_POPULAR_MEDIA_SUCCESS,LIST_POPULAR_MEDIA_ERROR,

	READ_MEDIA_REQUEST,READ_MEDIA_SUCCESS,READ_MEDIA_ERROR,

	UPDATE_MEDIA_REQUEST,UPDATE_MEDIA_SUCCESS,UPDATE_MEDIA_ERROR,

	REMOVE_MEDIA_REQUEST,REMOVE_MEDIA_SUCCESS,REMOVE_MEDIA_ERROR,
}