

const LOGIN_USER_REQUEST = 'Signin page/LOGIN_USER_REQUEST';
const LOGIN_USER_SUCCESS = 'Api response/LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'Api response/LOGIN_USER_ERROR';

const REGISTER_USER_REQUEST = 'Signup page/REGISTER_USER_REQUEST';
const REGISTER_USER_SUCCESS = 'Api response/REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR = 'Api response/REGISTER_USER_ERROR';

const UPDATE_USER_REQUEST = 'Profile/history page/UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS = 'Api response/UPDATE_USER_SUCCESS';
const UPDATE_USER_ERROR = 'Api response/UPDATE_USER_ERROR';

const GET_USERS_CHANNELS_REQUEST = 'Channels component/GET_USERS_CHANNELS_REQUEST';
const GET_USERS_CHANNELS_SUCCESS = 'Api response/GET_USERS_CHANNELS_SUCCESS';
const GET_USERS_CHANNELS_ERROR = 'Api response/GET_USERS_CHANNELS_ERROR';


const REMOVE_VIEW_HISTORY_REQUEST = 'History page/REMOVE_VIEW_HISTORY_REQUEST';
const REMOVE_VIEW_HISTORY_SUCCESS = 'Api response/REMOVE_VIEW_HISTORY_SUCCESS';
const REMOVE_VIEW_HISTORY_ERROR = 'Api response/REMOVE_VIEW_HISTORY_ERROR';

const ADD_TO_WATCH_LATER_REQUEST = 'Watch later page/ADD_TO_WATCH_LATER_REQUEST';
const ADD_TO_WATCH_LATER_SUCCESS = 'Api response/ADD_TO_WATCH_LATER_SUCCESS';
const ADD_TO_WATCH_LATER_ERROR = 'Api response/ADD_TO_WATCH_LATER_ERROR';


export default {
	LOGIN_USER_REQUEST,LOGIN_USER_SUCCESS,LOGIN_USER_ERROR,

	REGISTER_USER_REQUEST,REGISTER_USER_SUCCESS,REGISTER_USER_ERROR,

	UPDATE_USER_REQUEST,UPDATE_USER_SUCCESS,UPDATE_USER_ERROR,
	REMOVE_VIEW_HISTORY_REQUEST,REMOVE_VIEW_HISTORY_SUCCESS,REMOVE_VIEW_HISTORY_ERROR,

	ADD_TO_WATCH_LATER_REQUEST,ADD_TO_WATCH_LATER_SUCCESS,ADD_TO_WATCH_LATER_ERROR,

	GET_USERS_CHANNELS_REQUEST,GET_USERS_CHANNELS_SUCCESS,GET_USERS_CHANNELS_ERROR
}