

const LOGIN_USER_REQUEST = 'Signin page/LOGIN_USER_REQUEST';
const LOGIN_USER_SUCCESS = 'Api response/LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'Api response/LOGIN_USER_ERROR';

const REGISTER_USER_REQUEST = 'Signup page/REGISTER_USER_REQUEST';
const REGISTER_USER_SUCCESS = 'Api response/REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR = 'Api response/REGISTER_USER_ERROR';



export default {
	LOGIN_USER_REQUEST,LOGIN_USER_SUCCESS,LOGIN_USER_ERROR,

	REGISTER_USER_REQUEST,REGISTER_USER_SUCCESS,REGISTER_USER_ERROR
}