

const LOGIN_USER_REQUEST = 'Signin page/LOGIN_USER_REQUEST';
const LOGIN_USER_SUCCESS = 'Api response/LOGIN_USER_SUCCESS';
const LOGIN_USER_ERROR = 'Api response/LOGIN_USER_ERROR';

const REGISTER_USER_REQUEST = 'Signup page/REGISTER_USER_REQUEST';
const REGISTER_USER_SUCCESS = 'Api response/REGISTER_USER_SUCCESS';
const REGISTER_USER_ERROR = 'Api response/REGISTER_USER_ERROR';

const UPDATE_HISTORY_SETTINGS_REQUEST = 'History page/UPDATE_HISTORY_SETTINGS_REQUEST';
const UPDATE_HISTORY_SETTINGS_SUCCESS = 'Api response/UPDATE_HISTORY_SETTINGS_SUCCESS';
const UPDATE_HISTORY_SETTINGS_ERROR = 'Api response/UPDATE_HISTORY_SETTINGS_ERROR';


const REMOVE_VIEW_HISTORY_REQUEST = 'History page/REMOVE_VIEW_HISTORY_REQUEST';
const REMOVE_VIEW_HISTORY_SUCCESS = 'Api response/REMOVE_VIEW_HISTORY_SUCCESS';
const REMOVE_VIEW_HISTORY_ERROR = 'Api response/REMOVE_VIEW_HISTORY_ERROR';



export default {
	LOGIN_USER_REQUEST,LOGIN_USER_SUCCESS,LOGIN_USER_ERROR,

	REGISTER_USER_REQUEST,REGISTER_USER_SUCCESS,REGISTER_USER_ERROR,

	UPDATE_HISTORY_SETTINGS_REQUEST,UPDATE_HISTORY_SETTINGS_SUCCESS,UPDATE_HISTORY_SETTINGS_ERROR,
	REMOVE_VIEW_HISTORY_REQUEST,REMOVE_VIEW_HISTORY_SUCCESS,REMOVE_VIEW_HISTORY_ERROR,


}