

const GET_CHANNELS_TOPICS_REQUEST = 'Create channel modal/GET_CHANNELS_TOPICS_REQUEST';
const GET_CHANNELS_TOPICS_SUCCESS = 'Api response/GET_CHANNELS_TOPICS_SUCCESS';
const GET_CHANNELS_TOPICS_ERROR = 'Api response/GET_CHANNELS_TOPICS_ERROR';

const CREATE_NEW_CHANNEL_REQUEST = 'Create channel modal/CREATE_NEW_CHANNEL_REQUEST';
const CREATE_NEW_CHANNEL_SUCCESS = 'Api response/CREATE_NEW_CHANNEL_SUCCESS';
const CREATE_NEW_CHANNEL_ERROR = 'Api response/CREATE_NEW_CHANNEL_ERROR';

const GET_CHANNEL_BY_SLUG_REQUEST = 'Create channel modal/GET_CHANNEL_BY_SLUG_REQUEST';
const GET_CHANNEL_BY_SLUG_SUCCESS = 'Api response/GET_CHANNEL_BY_SLUG_SUCCESS';
const GET_CHANNEL_BY_SLUG_ERROR = 'Api response/GET_CHANNEL_BY_SLUG_ERROR';

const GET_CHANNEL_MEDIA_REQUEST = 'Channel page/GET_CHANNEL_MEDIA_REQUEST';
const GET_CHANNEL_MEDIA_SUCCESS = 'Api response/GET_CHANNEL_MEDIA_SUCCESS';
const GET_CHANNEL_MEDIA_ERROR = 'Api response/GET_CHANNEL_MEDIA_ERROR';

const UPDATE_CHANNEL_REQUEST = 'Channel page/UPDATE_CHANNEL_REQUEST';
const UPDATE_CHANNEL_SUCCESS = 'Api response/UPDATE_CHANNEL_SUCCESS';
const UPDATE_CHANNEL_ERROR = 'Api response/UPDATE_CHANNEL_ERROR';

const SUBSCRIBETO_CHANNEL_REQUEST = 'Channel page/SUBSCRIBETO_CHANNEL_REQUEST';
const SUBSCRIBETO_CHANNEL_SUCCESS = 'Api response/SUBSCRIBETO_CHANNEL_SUCCESS';
const SUBSCRIBETO_CHANNEL_ERROR = 'Api response/SUBSCRIBETO_CHANNEL_ERROR';
const UNSUBSCRIBEFROM_CHANNEL_REQUEST = 'Channel page/UNSUBSCRIBEFROM_CHANNEL_REQUEST';
const UNSUBSCRIBEFROM_CHANNEL_SUCCESS = 'Api response/UNSUBSCRIBEFROM_CHANNEL_SUCCESS';
const UNSUBSCRIBEFROM_CHANNEL_ERROR = 'Api response/UNSUBSCRIBEFROM_CHANNEL_ERROR';


export default {
	GET_CHANNELS_TOPICS_REQUEST,GET_CHANNELS_TOPICS_SUCCESS,GET_CHANNELS_TOPICS_ERROR,

	CREATE_NEW_CHANNEL_REQUEST,CREATE_NEW_CHANNEL_SUCCESS,CREATE_NEW_CHANNEL_ERROR,

	GET_CHANNEL_BY_SLUG_REQUEST,GET_CHANNEL_BY_SLUG_SUCCESS,GET_CHANNEL_BY_SLUG_ERROR,

	GET_CHANNEL_MEDIA_REQUEST,GET_CHANNEL_MEDIA_SUCCESS,GET_CHANNEL_MEDIA_ERROR,

	UPDATE_CHANNEL_REQUEST,UPDATE_CHANNEL_SUCCESS,UPDATE_CHANNEL_ERROR,

	SUBSCRIBETO_CHANNEL_REQUEST,SUBSCRIBETO_CHANNEL_SUCCESS,SUBSCRIBETO_CHANNEL_ERROR,
	UNSUBSCRIBEFROM_CHANNEL_REQUEST,UNSUBSCRIBEFROM_CHANNEL_SUCCESS,UNSUBSCRIBEFROM_CHANNEL_ERROR
}