

const GET_CHANNELS_TOPICS_REQUEST = 'Create channel modal/GET_CHANNELS_TOPICS_REQUEST';
const GET_CHANNELS_TOPICS_SUCCESS = 'Api response/GET_CHANNELS_TOPICS_SUCCESS';
const GET_CHANNELS_TOPICS_ERROR = 'Api response/GET_CHANNELS_TOPICS_ERROR';

const CREATE_NEW_CHANNEL_REQUEST = 'Create channel modal/CREATE_NEW_CHANNEL_REQUEST';
const CREATE_NEW_CHANNEL_SUCCESS = 'Api response/CREATE_NEW_CHANNEL_SUCCESS';
const CREATE_NEW_CHANNEL_ERROR = 'Api response/CREATE_NEW_CHANNEL_ERROR';


export default {
	GET_CHANNELS_TOPICS_REQUEST,GET_CHANNELS_TOPICS_SUCCESS,GET_CHANNELS_TOPICS_ERROR,

	CREATE_NEW_CHANNEL_REQUEST,CREATE_NEW_CHANNEL_SUCCESS,CREATE_NEW_CHANNEL_ERROR

}