

const GET_CHANNELS_TOPICS_REQUEST = 'Create channel modal/GET_CHANNELS_TOPICS_REQUEST';
const GET_CHANNELS_TOPICS_SUCCESS = 'Api response/GET_CHANNELS_TOPICS_SUCCESS';
const GET_CHANNELS_TOPICS_ERROR = 'Api response/GET_CHANNELS_TOPICS_ERROR';


export default {
	GET_CHANNELS_TOPICS_REQUEST,GET_CHANNELS_TOPICS_SUCCESS,GET_CHANNELS_TOPICS_ERROR

}